import type { Metadata } from "next";
import localFont from "next/font/local";
import "./global.css";
import { Analytics } from "@vercel/analytics/next";
import { ToastProvider } from "@/components/ui/toast";

const jost = localFont({
  src: "./fonts/Jost-VariableFont_wght.ttf",
  variable: "--font-jost",
  weight: "100 800",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Analytics />
      <body className={` ${jost.variable} antialiased`}>
        <ToastProvider>{children}</ToastProvider>
      </body>
    </html>
  );
}
